### ISSUE TITLE
Support SNI

### ISSUE THREAD

**Issue by natefoo** [usegalaxy-eu/ansible-certbot#11]
Currently the role combines all of the domains in `certbot_domains` into a single execution of `certbot certonly ... -d {{ ','.join(certbot_domains) }}`, which gets you a single cert with multiple `subjectAltName`s. It's desirable in some cases to use SNI instead and thus get multiple certs (which themselves may have `subjectAltName`s).

This could be done in a multitude of ways, maybe the simplest would be a new variable:

```yaml
certbot_sni_domains:
  example.org:
    - example.org
    - www.example.org
  example.com:  # no sANs
```

This should just need to run the `certbot certonly` task in `request-cert.yml` once per dict key in order to generate the certs.
